export enum Actions {
   RIGHTSIDEBAR_CHANGE_VIEW = "RIGHTSIDEBAR_CHANGE_VIEW",
   ACCOUNT_SETTINGS_UPDATE = "ACCOUNT_SETTINGS_UPDATE",
   ACCOUNT_PASSWORD_CHANGE = "ACCOUNT_PASSWORD_CHANGE",
   AUTH_SIGN_IN = "AUTH_SIGN_IN",
   AUTH_LOGOUT = "AUTH_LOGOUT",
}
